name: web-unit-tests
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Set up Go 1.24.2
        uses: actions/setup-go@v1
        with:
          go-version: 1.24.2
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Run unit tests (exclude integration tests)
        run: |
          cd web7
          go test -v -timeout 5m ./api/... ./services/...
